#pragma once
#include <QtCore/qglobal.h>

#if defined(COREPERSISTENCE_LIBRARY)
#  define COREPERSISTENCE_EXPORT Q_DECL_EXPORT
#  define QX_REGISTER_HPP_USER QX_REGISTER_HPP_EXPORT_DLL
#  define QX_REGISTER_CPP_USER QX_REGISTER_CPP_EXPORT_DLL
#else
#  define COREPERSISTENCE_EXPORT Q_DECL_IMPORT
#  define QX_REGISTER_HPP_USER QX_REGISTER_HPP_IMPORT_DLL
#  define QX_REGISTER_CPP_USER QX_REGISTER_CPP_IMPORT_DLL
#endif
